# Generated by Django 5.2.8 on 2025-11-09 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaguestanding',
            name='away_draws',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leaguestanding',
            name='away_losses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leaguestanding',
            name='away_wins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leaguestanding',
            name='clean_sheets',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leaguestanding',
            name='failed_to_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leaguestanding',
            name='home_draws',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leaguestanding',
            name='home_losses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leaguestanding',
            name='home_wins',
            field=models.IntegerField(default=0),
        ),
    ]
