# Generated by Django 5.2.8 on 2025-11-09 09:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_leaguestanding_away_draws_leaguestanding_away_losses_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(choices=[('GK', 'Goalkeeper'), ('DF', 'Defender'), ('MF', 'Midfielder'), ('FW', 'Forward')], max_length=2)),
                ('nationality', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('height', models.IntegerField(blank=True, help_text='Height in cm', null=True)),
                ('weight', models.IntegerField(blank=True, help_text='Weight in kg', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('is_penalty', models.BooleanField(default=False)),
                ('is_own_goal', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='api.game')),
                ('assistant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assists', to='api.player')),
                ('scorer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='api.player')),
            ],
            options={
                'ordering': ['game', 'minute'],
            },
        ),
        migrations.AddField(
            model_name='game',
            name='away_team_players',
            field=models.ManyToManyField(related_name='away_games_played', to='api.player'),
        ),
        migrations.AddField(
            model_name='game',
            name='home_team_players',
            field=models.ManyToManyField(related_name='home_games_played', to='api.player'),
        ),
        migrations.CreateModel(
            name='PlayerContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(help_text='Squad number')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='api.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='api.team')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
