# Generated by Django 5.2.8 on 2025-11-09 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_player_goal_game_away_team_players_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='players',
            field=models.ManyToManyField(related_name='teams', through='api.PlayerContract', to='api.player'),
        ),
    ]
